# Hiroki OS / Muz pacman repository fragment
# Install by copying this file to /etc/pacman.d/muz.conf
# and ensure it is included from /etc/pacman.conf with:
# Include = /etc/pacman.d/*.conf

[HirokiOS]
SigLevel = Never
Server = https://hiroki-systems.github.io/Hiroki-OS-Neox-Packages/$arch
